# Generated by Django 2.2.3 on 2019-07-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20190727_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
        migrations.DeleteModel(
            name='CustomerType',
        ),
    ]
