# Generated by Django 2.2.3 on 2019-07-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20190727_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertype',
            name='customer_type',
            field=models.CharField(max_length=50),
        ),
    ]
